### ISSUE TITLE
Does not compile on 32 bit windows

### ISSUE THREAD

**Issue by robeady** [veeenu/hudhook#1]
Background: I'm attempting to hook PCSX2 which is a 32-bit process. Because hooking involves looking up the address of Kernel32::LoadLibraryA, it seems convenient if the hooking process is also 32-bit (see https://stackoverflow.com/questions/8776437/c-injecting-32-bit-targets-from-64-bit-process).

Unfortunately I cannot compile this crate with the "i686-pc-windows-msvc" target.

```
   Compiling hudhook v0.1.5
error[E0308]: mismatched types
   --> .cargo\registry\src\github.com-1ecc6299db9ec823\hudhook-0.1.5\src\hook.rs:101:9
    |
101 |         wnd_proc as WndProc as isize,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `isize`
    |
help: you can convert an `isize` to an `i32` and panic if the converted value doesn't fit
    |
101 |         (wnd_proc as WndProc as isize).try_into().unwrap(),
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I tried to investigate this and it would appear that under 32-bit windows, `SetWindowLongPtrA` is redefined as `SetWindowLongA` which takes a `LONG` 3rd argument. Rust is not happy about treating this as an `isize` for reasons I do not completely understand. I'm unsure if the suggestion of `(wnd_proc as WndProc as isize).try_into().unwrap()` is a sensible solution.

**Comment by robeady** [comment]
This issue appeared in another repo: https://github.com/linebender/druid/issues/9

the fix was: https://github.com/linebender/druid/pull/1563/files#diff-c77d3b86d02daed92261a43fb53b6b392a43066402eb74f3cbd542d01ab99dd5L333

I will open a PR with that fix.

**Comment by veeenu** [comment]
Hi Rob, thank you for your contribution! You make a really good point and there probably are many more instances of such casts that could be reworked to be slimmer/more idiomatic, especially in that particular module which is full of `unsafe` and Win32-related machinery. Unfortunately I haven't spent too much time validating compatibility for anything other than x64 and it'd be a good idea if I did.

**Comment by robeady** [comment]
No problem :) I think there are indeed some unnecessary casts/transmutes scattered in there, but I don't know enough to be sure of it. This was the only compilation issue at least.
