### ISSUE TITLE
WND proc not reset on DX12 hook

### ISSUE THREAD

**Issue by OneXDeveloper** [veeenu/hudhook#10]
Hi,

Firstly, thanks for this project. 

I have been working on getting unhooking working on my tool and have got it working with one exception. The WND proc is not resetting after disabling hooks so the game will crash.

I didn’t want to PR my (probably wrong) approach because it felt pretty nasty and hacky. But the gist is that you need to call `SetWindowLongPtrA` with the original WND proc. You can get the original one by calling `GetWindowLongPtrA` with the hwnd in the `new` function of the `ImguiRenderer` and just save it somewhere until it’s time to shutdown. I had to create some functions to expose a shutdown method on the imgui renderer in the hook module and that felt weird. I’m sure you’d find a better way to handle that. 

Thanks again.

**Comment by veeenu** [comment]
Oh, that is not a hack! There may be more or less clean ways of going about it, but definitely having a destructor kind of thing is a good idea -- after all, RAII is **the** pattern in Rust.

Feel free to share your PR if you'd like to! Even if it didn't fit with the code style for the rest of the code, it'd still be a great contribution and would help me figure out how to get some things right in the implementation -- and I could always request changes or modify it afterwards anyway.

Unhooking has been planned for a while, just never really figured out how to get it going properly. So thank you!

**Comment by veeenu** [comment]
I noticed I am already storing the window proc in `ImguiRenderer`, see [this](https://github.com/veeenu/hudhook/blob/master/hudhook/src/hooks/dx12.rs#L523-L526); `cleanup` is invoked in the `ResizeBuffers` hook, like [this](
https://github.com/veeenu/hudhook/blob/master/hudhook/src/hooks/dx12.rs#L143-L162): the `ImguiRenderer` is just taken out of the `OnceCell` and later on recreated.

Is this similar to your solution?

**Comment by OneXDeveloper** [comment]
The one you’re storing is the overridden one though. Not the original from the process. I wasn’t sure why you were doing that. But yes, very similar. The only difference really is I created a shutdown function, that I call from my detach, that did the same thing but with the one originally from the process. I obtained that with the get function I shared above. The unhooking and everything else was working great.

**Comment by veeenu** [comment]
How/where did you write your detach function? I tried calling `FreeLibraryAndExitThread` from inside the UI loop but that resulted in crashing, as the function does not return and so its whole call stack doesn't get to do any cleanup.

> The one you’re storing is the overridden one though.

I'm not sure that's the case:

- [Here](https://github.com/veeenu/hudhook/blob/master/hudhook/src/hooks/dx12.rs#L367-L371) we're retrieving the preexisting `wnd_proc` value: as stated by [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra), _"If the function succeeds, the return value is the previous value of the specified offset."_
- [Here](https://github.com/veeenu/hudhook/blob/master/hudhook/src/hooks/dx12.rs#L413) we're storing it in the `ImguiRenderer` instance.
- [Here](https://github.com/veeenu/hudhook/blob/master/hudhook/src/hooks/dx12.rs#L265-L270) we are retrieving that `wnd_proc` value, and forwarding non-consumed events to it; if we didn't do that, the game wouldn't be able to receive some important events at all.

**Comment by OneXDeveloper** [comment]
Oh, I didn’t realize that function returned the preexisting one. What is that cleanup function called from? It reads like resize so I’m guessing it could be called a lot. What happens if it’s called multiple times? Would it lose the original or the hooked one?

> How/where did you write your detach function? I tried calling FreeLibraryAndExitThread from inside the UI loop but that resulted in crashing, as the function does not return and so its whole call stack doesn't get to do any cleanup.

I created a static mutex and condvar. I locked the mutex in my render loop and if they click the exit button I set it to true and notify all on the condvar. In my attach, I spawn a thread that blocks on the condvar. Once that triggers and the mutex is set to true then I free library.

**Comment by veeenu** [comment]
> What happens if it’s called multiple times? Would it lose the original or the hooked one?

It should not be called multiple times, only in the event that there is an actual window resize. We have a lax guarantee that it will not be called twice in a row as the renderer object will be dropped afterwards, to be recreated at the next invocation of `Present`.

> I created a static mutex and condvar. I locked the mutex in my render loop and if they click the exit button I set it to true and notify all on the condvar. In my attach, I spawn a thread that blocks on the condvar. Once that triggers and the mutex is set to true then I free library.

That's a nice approach!

In #11, I instead opted for building a function that spawns its own thread, unhooks everything and frees the library. You can call it from anywhere in your render loop via `hudhook::lifecycle::eject()`. I'm not 100% sure on concurrency issues but I have been testing it for a bit and found no problems with it.

**Comment by OneXDeveloper** [comment]
Just was able to test this. Working great! Thanks again :)
