### ISSUE TITLE
`ImguiRenderLoopFlags` is never updated

### ISSUE THREAD

**Issue by veeenu** [veeenu/hudhook#120]
Currently, the `ImguiRenderLoopFlags::focused` flag is never updated anywhere in the code. 

We should get rid of it until we find a better way of querying the focus state. 

This will result in a breaking change, but it is for the best as it will simplify the API.

**Comment by vars1ty** [comment]
If you're talking about checking the focus state for whether or not an ImGui window is focused, `ui.io().want_capture_mouse` could do.

**Comment by veeenu** [comment]
Indeed that might be the case, as these are the instances where I personally use that, and both also refer to `want_capture`:

- [Dark Souls III practice tool](https://github.com/search?q=repo%3Aveeenu%2Fdarksoulsiii-practice-tool+focused&type=code)
- [Elden Ring practice tool](https://github.com/search?q=repo%3Aveeenu%2Feldenring-practice-tool%20focused&type=code)
