### ISSUE TITLE
Encountered an issue while using the Example Dx11 Hook with Dx11Game Rune Factory 5

### ISSUE THREAD

**Issue by vSylva** [veeenu/hudhook#130]
![GIF 2023-8-27 23-19-53](https://github.com/veeenu/hudhook/assets/58687743/77c4db00-eff0-420f-b69c-4430b45acc2a)
===

hudhook rev [3b86352](https://github.com/veeenu/hudhook/commit/3b86352420b37bcc1dc3208334d467837d6230d6)

The game is unable to respond to the mouse and keyboard inputs properly.

No ERROR is displayed on the console.

After pressing a key, the game responds multiple times to the pressed key after a few seconds. Mouse clicks require multiple attempts, and the response is delayed by a few seconds.

From the example dx11_hook
===
```rust
use hudhook::hooks::dx11::ImguiDx11Hooks;
use hudhook::hooks::ImguiRenderLoop;

use tracing::metadata::LevelFilter;
struct Dx11HookExample;

impl Dx11HookExample {
    fn new() -> Self {
        println!("Initializing");
        hudhook::alloc_console().expect("AllocConsole");
        hudhook::enable_console_colors();

        tracing_subscriber::fmt()
            .with_max_level(LevelFilter::ERROR)
            .with_thread_ids(true)
            .with_file(true)
            .with_line_number(true)
            .with_thread_names(true)
            .init();

        Dx11HookExample
    }
}

impl ImguiRenderLoop for Dx11HookExample {
    fn render(&mut self, _ui: &mut imgui::Ui) {
        // ui.window("Hello world").size([300.0, 110.0], Condition::FirstUseEver).build(|| {
        //     ui.text("Hello world!");
        //     ui.text("こんにちは世界！");
        //     ui.text("This...is...imgui-rs!");
        //     ui.separator();
        //     let mouse_pos = ui.io().mouse_pos;
        //     ui.text(format!("Mouse Position: ({:.1},{:.1})", mouse_pos[0], mouse_pos[1]));
        // });
    }
}

hudhook::hudhook!(Dx11HookExample::new().into_hook::<ImguiDx11Hooks>());
```

**Comment by vSylva** [comment]
I have tried multiple methods, but still unable to resolve the issue🤷
I performed hooking using C++ and rendered an ImGui demo window, and did not encounter the aforementioned issues.

**Comment by vSylva** [comment]
> It looks like mouse inputs are being translated incorrectly somewhere.
> 
> The most likely culprit should be the [new raw input system](https://github.com/veeenu/hudhook/blob/main/src/hooks/common/wnd_proc.rs) or possibly something to do with [client rects](https://github.com/veeenu/hudhook/pull/110/files).
> 
> This new input system is rather recent and I've only personally tested it against the ds3 and er practice tools (and the integration test cases).
> 
> Could you try with a much earlier version of `hudhook` ([this commit](https://github.com/veeenu/hudhook/commit/04264eeed61c733add984f17ca6cee74dd93628c) is the last one without the input system) and report whether it still fails or it behaves correctly?
> 
> (P.S. thank you for reporting this, I was about to release 0.5 but I want this to be fixed before that happens.)

I conducted new tests using ver 0.4, and the issues still persist.
In two other games, Sekiro and Raft, ver 0.4 and 0.5 can successfully hook

**Comment by veeenu** [comment]
Could you try running [ReShade](https://reshade.me/) against the game, and check whether you get similar behavior? If everything works ok with it, this is probably not dependent on the input processing but on something else. If ReShade has similar problems, I'm not sure how to proceed.

**Comment by vSylva** [comment]
> Could you try running [ReShade](https://reshade.me/) against the game, and check whether you get similar behavior? If everything works ok with it, this is probably not dependent on the input processing but on something else. If ReShade has similar problems, I'm not sure how to proceed.

ReShade 5.9.2 successfully hooked, and MSI Afterburner was also successfully hooked.

**Comment by vSylva** [comment]
A new issue has emerged where injection into the DX11 game 'Richman 10' results in this situation. This problem does not occur when using a test DLL written in C++.

hudhook
===
![2](https://github.com/veeenu/hudhook/assets/58687743/10f47e31-87dd-46a9-8a96-c30b884a9c0e)
![1](https://github.com/veeenu/hudhook/assets/58687743/2fa45541-fa40-48ca-a559-ee9efcacddfd)

cpp
===
![cpp](https://github.com/veeenu/hudhook/assets/58687743/15ea2062-f14c-4e45-86dd-34c5f39c5bd4)

**Comment by vSylva** [comment]
> Which hooking engine does the C++ version use? I think we could compare DX11 hook implementations and see what we got wrong.
> 
> P.S. these "insufficient display size" errors are common when the game window is minimized. Otherwise it means the game has more than one hwnd and we got the wrong one somehow.

This one https://gist.github.com/vSylva/d776b2579308f45c67af05532c01ee83

**Comment by veeenu** [comment]
I see you are using imgui's own dx11 renderer which may have deviated from my implementation over time. Your C++ resize hook impl is also much simpler in flow than mine, so that could also be a possible culprit.

I'm honestly not sure what could trigger this. I have briefly looked into it but it's probably going to take me quite a bit of time to find all the similarities/differences. I very much want to see this solved though as I want to target as wide a coverage as possible.

**Comment by vSylva** [comment]
> I see you are using imgui's own dx11 renderer which may have deviated from my implementation over time. Your C++ resize hook impl is also much simpler in flow than mine, so that could also be a possible culprit.
> 
> I'm honestly not sure what could trigger this. I have briefly looked into it but it's probably going to take me quite a bit of time to find all the similarities/differences. I very much want to see this solved though as I want to target as wide a coverage as possible.

Haha, i prefer hudhook over cpp, this problem is really giving a headache

**Comment by veeenu** [comment]
Glad to see at least the input errors and the weird artifacts are gone. I think the blackout issue could stem from the fact that currently we're not backing up the renderer state and so it gets completely overridden.

For some reason my state backup code is consistently crashing so I commented that out until I figure out why.

As an aside, I want to build more complex test harnesses (a rotating cube would be enough) in order to have a "closer to real life" testbed.

**Comment by veeenu** [comment]
@vSylva I have added state backup back to Dx11. It _should_ not crash now. Could you please give richman10 another spin?

**Comment by vSylva** [comment]
> @vSylva I have added state backup back to Dx11. It _should_ not crash now. Could you please give richman10 another spin?

Thank you
A new issue has arisen: injection causes a crash

![image](https://github.com/veeenu/hudhook/assets/58687743/b03c6332-9f14-4e4d-8541-1f590a387cf9)

**Comment by vSylva** [comment]
[78c8d21](https://github.com/veeenu/hudhook/commit/78c8d219931de12a3b39988023f8eea84421bc0c)

It appears to be working well

![image](https://github.com/veeenu/hudhook/assets/58687743/d9537714-5ece-4b9e-bd35-ce027e37bd86)
