### ISSUE TITLE
Inject not a function

### ISSUE THREAD

**Issue by KendrickFerguson** [veeenu/hudhook#133]
### this is my main.rs

use std::process::Command; 
use hudhook::inject;

fn main() {
  let mut child = Command::new("my_dx11_application.exe")
  .spawn()
  .expect("Failed to run child process");
  std::thread::sleep(std::time::Duration::from_millis(250));

  inject::inject("my_dx11_application.exe", "target/release/libmycrate.dll").ok();

  child.wait().expect("Child process error");
  tauri::Builder::default()
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
   
}

### This error appear when i run

error[E0425]: cannot find function `inject` in module `inject`
  --> src\main.rs:12:11
   |
12 |   inject::inject("my_dx11_application.exe", "target/release/libmycrate.dll").ok();
   |           ^^^^^^ not found in `inject`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `app` (bin "app") due to previous error

**Comment by veeenu** [comment]
The `inject` function was removed [almost a year ago](https://github.com/veeenu/hudhook/pull/46) in favor of a new API.

Where did you find documentation suggesting to use it instead of the new one? If there is any piece of documentation that still refers to it, we should remove it.

**Comment by KendrickFerguson** [comment]
In your readme in this code/document. please fix this so i can move forward.

**Comment by veeenu** [comment]
Nothing's blocking you from moving forward. I will fix the README but the current stable API is already [documented elsewhere](https://veeenu.github.io/hudhook/injecting-library/injecting.html) and you can refer to that.

**Comment by veeenu** [comment]
Nothing's blocking you from moving forward. I will fix the README but the stable API is [already documented elsewhere](https://veeenu.github.io/hudhook/injecting-library/injecting.html) and you can refer to that.

**Comment by veeenu** [comment]
Closed by #134
