### ISSUE TITLE
Replace texture image data

### ISSUE THREAD

**Issue by veeenu** [veeenu/hudhook#147]
Currently, a texture can only be loaded once via `RenderEngine::load_image` and its contents cannot be changed.

A public `RenderEngine::replace_image` method should be created to make this happen.

**Comment by misdake** [comment]
Also texture upload RowPitch has to be aligned to 256 bytes.
Might fix that first to support any image width (instead of multiple of 64).

**Comment by misdake** [comment]
For dx11 and dx12, uploadbuffer RowPitch must be aligned to 256 bytes (64 pixels). Might also fix this to support images with arbitrary width.

**Comment by veeenu** [comment]
That's an unrelated issue -- could you please open a new one so we can track that separately?

**Comment by misdake** [comment]
I did some experiments early today, but on an old version 799032ba from Jan, when there was only DX12 renderer. 

I split `create_texture_inner` into `create_texture_inner `+ `upload_texture_inner`, then added `replace_image` to RenderEngine. 

Here is the quick patch file for future reference. I haven't written any raw DX12 before, so there might be some bugs.
[split_create_texture_and_upload_texture.patch](https://github.com/veeenu/hudhook/files/14588411/split_create_texture_and_upload_texture.patch) on 799032ba

When I have some more spare time, I will take a look at renderers of other APIs.

**Comment by veeenu** [comment]
That's a good starting point, thank you!
