### ISSUE TITLE
Outdated HookBuilder documentation

### ISSUE THREAD

**Issue by vars1ty** [veeenu/hudhook#150]
https://github.com/veeenu/hudhook/blob/778d58b6062777eb07c41dda79a79646a515f78b/src/lib.rs#L353

That's the old usage, whereas the new one changed `with` to for example, this: `.with::<ImguiOpenGl3Hooks>(MyUI::new())`

**Comment by veeenu** [comment]
Thank you for reporting that, must've slipped!
