### ISSUE TITLE
Errors on Resident Evil 2 and Testing on Other Games

### ISSUE THREAD

**Issue by vSylva** [veeenu/hudhook#155]
![{7BEBC450-7DF1-4a5c-9C75-36ADAF8AF010}](https://github.com/veeenu/hudhook/assets/58687743/18c61117-6808-43ad-a4ca-a2a6b10cecab)
---

https://github.com/veeenu/hudhook/blob/heck-dcomp/examples/simple_hook.rs

Injecting "simple_hook.dll" after the game's logo appears will result in the aforementioned error. 
Injecting it after the game's main menu appears allows it to run properly. 

OGL game Rune Factory 4, DX11 game Sekiro, DX12 game Resident Evil 3 perform well.

**Comment by veeenu** [comment]
That branch is in a broken state, dx9 and opengl aren't done ye because I can't find a way to share their buffer. I'm working on a Vulkan renderer atm which *should* be able to deal with that iiuc.

**Comment by vSylva** [comment]
Sekiro (DX11) passed the test.
![image](https://github.com/veeenu/hudhook/assets/58687743/164e4e57-c8d2-4023-89c2-feceeeed229e)

Resident Evil 2 (DX12) and Resident Evil 3 (DX12) failed the test; once demo_hook_dx12.dll is injected, it will crash immediately. 
![image](https://github.com/veeenu/hudhook/assets/58687743/04aded38-8e2e-4a93-9c1b-ee83ee9fe4ab)

Rune Factory 4 (OGL3) cannot pass, error: ERROR ThreadId(02) hudhook::hooks::opengl3: src\hooks\opengl3.rs:92: Render error: Error { code: HRESULT(0x80070057), message: "Invalid parameter." }
![image](https://github.com/veeenu/hudhook/assets/58687743/1256491d-e8a2-4e94-947c-5b1435920a04)

**Comment by veeenu** [comment]
Thank you for testing these! I should probably add some observability, I'm not sure why those errors happen.

**Comment by vSylva** [comment]
> Thank you for testing these! I should probably add some observability, I'm not sure why those errors happen.

7bbbe06

(DX12) Resident Evil 2 and Resident Evil 3 appear to work well

![image](https://github.com/veeenu/hudhook/assets/58687743/3bf9e257-d97b-4e7e-9bd3-02281c5d1fd5)
![image](https://github.com/veeenu/hudhook/assets/58687743/9a683488-ea6a-403f-bf37-bc3d5d1070c9)

(DX11) Sekiro as well

![image](https://github.com/veeenu/hudhook/assets/58687743/e46b702f-fd60-4607-9cea-79a8006a77b4)

**Comment by veeenu** [comment]
Absolutely insane. Thank you for testing those @vSylva 

I have the OpenGL renderer left to do and then we can wrap this up and release 0.6.

**Comment by vSylva** [comment]
> Owner

GOOOOOOOOOOOOOOOOODDDDD
