### ISSUE TITLE
DX8

### ISSUE THREAD

**Issue by zhefenfei** [veeenu/hudhook#177]
is there any way impl dx8 idk

**Comment by veeenu** [comment]
I have no idea, I am skeptical about supporting it (DX9 is where I draw the line) but if you want to attempt it yourself feel free to open a PR

**Comment by zhefenfei** [comment]
> I have no idea, I am skeptical about supporting it (DX9 is where I draw the line) but if you want to attempt it yourself feel free to open a PR

Ok，i tried to update the dx8 to dx9.succeed.maybe it needn't impl dx8.thx
