### ISSUE TITLE
hudhook pipeline doesn't report `delta_time` to imgui runtime

### ISSUE THREAD

**Issue by ruby3141** [veeenu/hudhook#186]
According to imgui's custom backend implementation exhibit and first-party backend implementations,
`io.DeltaTime` is "usually" meant to be updated by backend code.

https://github.com/ocornut/imgui/blob/93daf232233dd0a68c6b0404d53b18e0d089b0d1/imgui.cpp#L334-L336
https://github.com/ocornut/imgui/blob/93daf232233dd0a68c6b0404d53b18e0d089b0d1/backends/imgui_impl_win32.cpp#L398
https://github.com/ocornut/imgui/blob/93daf232233dd0a68c6b0404d53b18e0d089b0d1/backends/imgui_impl_sdl3.cpp#L691

I think it's good to follow the convention for hudhook's custom imgui backend.

**Comment by veeenu** [comment]
That's a very good idea!
