### ISSUE TITLE
loading more then 8 textures doesn't work

### ISSUE THREAD

**Issue by asaadmohammed74** [veeenu/hudhook#195]
in the current master with DX12 , when trying to load more then 8 (the initial size of srv_heap) causes a heap resize, but all the textures created after the resize aren't rendered correctly. any textures added before the next resize will not be displayed.

to reproduce simply increase the `IMAGE_COUNT` in the dx12 test to more then 8

![image](https://github.com/user-attachments/assets/6f54ae88-07f8-4999-a40c-139c5ff156f1)
![image](https://github.com/user-attachments/assets/1532022b-1afc-4a8c-9b99-fb422f3e69e8)
![image](https://github.com/user-attachments/assets/92af6227-76d7-49d9-be0a-ce40c4e24408)

**Comment by veeenu** [comment]
Thank you for reporting this!

Probably we aren't transferring the textures from the old srv heap correctly.

**Comment by veeenu** [comment]
Could you please give #200 a spin? It _should_ solve the issue.
