### ISSUE TITLE
Discord link is broken.

### ISSUE THREAD

**Issue by luadebug** [veeenu/hudhook#213]
Discord link is broken. If it is intended to be like this just close this.
https://github.com/veeenu/hudhook/blob/465cb118f3fee0b7d57f83f19a53bb846f9527b3/README.md?plain=1#L7

**Comment by veeenu** [comment]
Thank you for reporting this! I have that invite in a few places and it routinely gets broken despite it being permanent. :shrug: 

Closing in #215.
