### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by veeenu** [veeenu/hudhook#23]
Some examples are broken, we should go back and review them.
As an added bonus, we should find a good strategy for end-to-end tests, i.e. creating dummy host applications and example overlays to be run over them, in order to exercise as much of the client API surface as possible.

```error[E0603]: struct `ImguiRenderLoopFlags` is private --> src\lib.rs:6:45 | 6 | use hudhook::hooks::dx11::{ImguiRenderLoop, ImguiRenderLoopFlags}; | ^^^^^^^^^^^^^^^^^^^^ private struct |
```

**Comment by happydpc** [comment]
I have compiled it ok,  try change to import these:
```rust
use hudhook::hooks::dx11::ImguiDX11Hooks;
use hudhook::hooks::{ImguiRenderLoop, ImguiRenderLoopFlags};
```
