### ISSUE TITLE
OpenGL support

### ISSUE THREAD

**Issue by Jakobzs** [veeenu/hudhook#24]
Hello,

I was wondering whether OpenGL support has been considered? Looking at the newly added DX9 renderer, there seems to be something similar [here](https://github.com/michaelfairley/rust-imgui-opengl-renderer). In case I attempt to tackle it myself, would it possible to PR it here?

**Comment by veeenu** [comment]
Hi!

Absolutely -- this would be very desirable, and PRs welcome. Thank you!
