### ISSUE TITLE
Tested on some GTA games, all good except GTA IV

### ISSUE THREAD

**Issue by x87** [veeenu/hudhook#29]
Hi there!

Recently found this project and tested v0.2.0 on a few games, notably Grand Theft Auto series. Here is what I got:

GTA III, GTA VC - did not work. They are old and use DirectX 8 so this might be expected. Tried [d3d8to9](https://github.com/crosire/d3d8to9), but no luck. Unofficial re-implementations known as re3/reVC worked since they use DX9.
GTA SA - worked with DX9 hook
Bully: SE 1.200 worked with DX9 hook
GTA Trilogy: The Definitive Edition - worked (x64 build with DX11 hook)
GTA V - worked (x64 build with DX11 hook)
GTA IV (The Complete Edition, Steam) - did not work. Tried both DX9 and DX11, tried injecting the hook on game launch or after a few minutes of playing. The game seems to function normally, but the overlay window simply does not appear. 

I understand the tool is in its early stages but maybe you can share some clues on where to look at to find a reason why it did not work on GTA IV?

Thanks in advance and good luck with the project.

**Comment by veeenu** [comment]
Hi!

wrt GTA III and VC support: no idea how `d3d8to9` may behave, but if DX8 is not _that_ different from DX9 the current DX9 renderer and hook could be adapted to DX8. I also suspect those games may be 32 bit, and that has not been a goal at all of this library (so far -- depends on adoption and interest I guess).

wrt GTA IV: there are a few things to be tried. First of all, use the debugging facilities (e.g. some logging library like `simplelog`) paired with the `AllocConsole`/`FreeConsole` helpers, or a file writer output, to determine whether the hook has found the right functions in the first place. You may check how the [practice tool](https://github.com/veeenu/eldenring-practice-tool/blob/main/practice-tool/src/lib.rs#L62-L128) does it for reference.

Afterwards you may want to dig deeper into the game, get a better understanding of which rendering engine it is using, if there are peculiarities about it that hudhook doesn't behave correctly with etc. Can't offer much help there unfortunately, it largely depends on the game.

Hope that helps and thank you!

**Comment by Godnoken** [comment]
Hello @x87!

Did you uset the i686-pc-windows-msvc target for the GTA: SA build? I can not inject my dll for that game and I'm curious how you got it to work.

**Comment by x87** [comment]
I used https://github.com/ThirteenAG/Ultimate-ASI-Loader

**Comment by veeenu** [comment]
_Should_ be closed by #39, feel free to reopen if it's still not working for you!
