### ISSUE TITLE
Document Rust nightly requirement

### ISSUE THREAD

**Issue by Godnoken** [veeenu/hudhook#32]
Hello there,

Wanted to give this crate a shot but unfortunately hit a bump on the road right away, hehe.

Detour2 0.9.0 uses #![feature] which is not allowed without nightly.

`error[E0554]: `#![feature]` may not be used on the stable release channel`

Not sure if the crate is meant to be ran on Rust nightly, and if that's the case, an update of the docs would be in place.

**Comment by veeenu** [comment]
Hey! Yeah, this crate is meant for Rust nightly as it relies on a number of unstable features. I'm planning a patch bump sometime soon and will add pertinent documentation.

**Comment by Godnoken** [comment]
Ah, yes. I probably should have realized that.

Cool! As of now I can't get it to work with any game and I'm not entirely sure why. Better documentation would help a bunch.

Might I suggest opening a discussion board on the repo? I believe it's better to steer clear from having to ask questions in issues.

**Comment by Godnoken** [comment]
> That's a very good idea -- never used discussions so far, but it's worth a shot :D
> 
> All in all, I see this library is getting a tiny bit of traction lately so I want to step it up and improve this repo in any way I can -- docs and ways to interact are good first candidates.

Cheers! I created the first discussion thread.

Awesome to hear, I'm happy to contribute in ways I can if I get it working for my app. Far from an experienced developer however.

**Comment by veeenu** [comment]
I started writing a [short book](https://veeenu.github.io/hudhook/) with a tutorial for using `hudhook`. It also addresses the fact that this is Rust nightly only.

**Comment by Godnoken** [comment]
> I started writing a [short book](https://veeenu.github.io/hudhook/) with a tutorial for using `hudhook`. It also addresses the fact that this is Rust nightly only.

Great stuff! This is exactly what you want to see when you use a new crate, especially as a newbie.

**Comment by veeenu** [comment]
Thank you, glad you like it! 😄 
You're right, it's hard to let go of the tunnel vision you accumulate by being as close to a project as I am, but it's absolutely fundamental that documentation be easily understandable by people who have less context than insiders.
Rust's documentation is great for exactly that reason, and I'll gladly take a page from that book 😅

**Comment by Godnoken** [comment]
> You're right, it's hard to let go of the tunnel vision you accumulate by being as close to a project as I am, but it's absolutely fundamental that documentation be easily understandable by people who have less context than insiders. Rust's documentation is great for exactly that reason, and I'll gladly take a page from that book 😅

Oh yes, completely understandable and near to impossible to always be looking at it from other's angles. Good thing you have newbs like me asking 'simple' questions 👀😁
