### ISSUE TITLE
Error while compiling (E0059)

### ISSUE THREAD

**Issue by ArefEghbaliDev** [veeenu/hudhook#54]
Hi , I tried to compile the code from documentation but I get this error:

error[E0059]: type parameter to bare `Fn` trait must be a tuple
   --> C:\Users\Aref\.cargo\registry\src\github.com-1ecc6299db9ec823\detour2-0.9.0\src\detours\statik.rs:106:8
    |
106 |     D: Fn<T::Arguments, Output = T::Output> + Send + 'static,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Tuple` is not implemented for `<T as Function>::Arguments`
    |
note: required by a bound in `Fn`
   --> C:\Users\Aref\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:159:20
    |
159 | pub trait Fn<Args: Tuple>: FnMut<Args> {
    |                    ^^^^^ required by this bound in `Fn`
help: consider further restricting the associated type
    |
106 |     D: Fn<T::Arguments, Output = T::Output> + Send + 'static, <T as Function>::Arguments: Tuple
    |                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0059]: type parameter to bare `Fn` trait must be a tuple
   --> C:\Users\Aref\.cargo\registry\src\github.com-1ecc6299db9ec823\detour2-0.9.0\src\detours\statik.rs:157:8
    |
157 |     C: Fn<T::Arguments, Output = T::Output> + Send + 'static,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Tuple` is not implemented for `<T as Function>::Arguments`
    |
note: required by a bound in `Fn`
   --> C:\Users\Aref\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:159:20
    |
159 | pub trait Fn<Args: Tuple>: FnMut<Args> {
    |                    ^^^^^ required by this bound in `Fn`
help: consider further restricting the associated type
    |
157 |     C: Fn<T::Arguments, Output = T::Output> + Send + 'static, <T as Function>::Arguments: Tuple
    |                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0059`.
error: could not compile `detour2` due to 2 previous errors

I followed the instructions in the documentation https://veeenu.github.io/hudhook/creating-library/project-setup.html

thanks.

**Comment by veeenu** [comment]
At the moment, the released version is in a broken state because of `detour2`, waiting on [this PR](https://github.com/lostinspiration/detour-rs/pull/1) to be merged.

For the time being, you should specify your dependency as
```toml
hudhook = { git = "https://github.com/veeenu.hudhook" }
```

I intend to publish a `0.3.0` release as soon as that PR is merged which should fix this issue, but I could revert to `minhook` and release anyway at some point soon.

**Comment by ArefEghbaliDev** [comment]
> At the moment, the released version is in a broken state because of `detour2`, waiting on [this PR](https://github.com/lostinspiration/detour-rs/pull/1) to be merged.
> 
> For the time being, you should specify your dependency as
> 
> ```toml
> hudhook = { git = "https://github.com/veeenu.hudhook" }
> ```
> 
> I intend to publish a `0.3.0` release as soon as that PR is merged which should fix this issue, but I could revert to `minhook` and release anyway at some point soon.

Thanks for reply, when I specify my dependency like that it throws this error: 

 request failed with status code: 404; class=Http (34)
 
 I think I have to wait until that pr is merged
