### ISSUE TITLE
Migrate to imgui-rs 0.10.0

### ISSUE THREAD

**Issue by veeenu** [veeenu/hudhook#62]

**Comment by veeenu** [comment]
Migration is currently blocked by michaelfairley/rust-imgui-opengl-renderer/pull/22.

I have decided to drop support for OpenGL3 for the time being as it's the only way we can move forward on our end. Once we find a way of having our own renderer, re-adding support will be trivial.

@Jakobzs would you be interested in trying to tackle writing an OpenGL rendering engine for `hudhook`, as opposed to using the external one? Sadly I have little to no knowledge of OpenGL myself and wouldn't know where to begin, though I feel confident I could easily manage incremental updates over time (especially if we end up implementing #42 as a form of regression testing).

**Comment by Jakobzs** [comment]
We talked it over on Discord. I decided to fork the `imgui-opengl-renderer` crate and create one called `imgui-opengl` that I'll be maintaining, primarily also cause it looks to be very low maintenance.

I have PR'ed a fix for OpenGL3 that includes the adding of the fork which contains the fixes for imgui 0.9.0.

**Comment by veeenu** [comment]
0.10.0 came out already, looking at the changelog it shouldn't have anything breaking on our side but it'll require a bump from all dependencies again. While 0.4 isn't released yet, might as well just bump that too.

**Comment by absencelul** [comment]
do you have an ETA of when this would be migrated to 0.10.0? @veeenu

**Comment by veeenu** [comment]
Probably not before April as this is a very very busy time of the year for me. 

There are also other issues scheduled for 0.4 that I'd like to get sorted. But I'll gladly accept and review PRs, and once that's in main one could use the GitHub link as dependency until 0.4 hits.

This particular one should be rather simple, essentially just bump deps and change stuff until it works again.

**Comment by veeenu** [comment]
Closed by #88
