### ISSUE TITLE
Initialize runs several times in a few games

### ISSUE THREAD

**Issue by Godnoken** [veeenu/hudhook#73]
I noticed that the ImguiRenderLoop initialize function will run several times if the DLL is injected early in certain games.

Examples: Mount & Blade: Warband (32bit, DX9), Niche (64bit, DX11), Oxygen Not Included (64bit, DX11).

Is this something you're aware of @veeenu or possibly have an idea of why that is happening?

The side effect of this is that the game input gets all whacked up. Sometimes a keypress or mouseclick gets 'locked' to keydown and sometimes you have to click several times before anything registers.

**Comment by Godnoken** [comment]
https://github.com/veeenu/hudhook/blob/4c2968d23d70d963e094db1ffacc8eeeba40c8f6/src/hooks/dx11.rs#L77

I know next to nothing about swap chains, but it seems that the ImguiRenderer gets invoked more than once inside of it in some cases.

**Comment by veeenu** [comment]
Hi! Sorry for the delay, been quite busy.

In some games (definitely DS3 and ER) not reinitializing the renderer means that the UI won't scale alongside resizing the window, at best, or crash, at worst.

The fact that it gets called multiple times with early injections makes me think that resize is just called pointlessly by the game/engine a number of times while nothing is still getting rendered yet -- I wouldn't say this is something `hudhook` should work around.

**Comment by Godnoken** [comment]
> Hi! Sorry for the delay, been quite busy.

No worries, no pressure, just happy to get a response eventually!

> In some games (definitely DS3 and ER) not reinitializing the renderer means that the UI won't scale alongside resizing the window, at best, or crash, at worst.

Aha! I suppose I should just make changes on my own end then. I have some functionality in the initialize function that I'd rather not have run more than once.

> The fact that it gets called multiple times with early injections makes me think that resize is just called pointlessly by the game/engine a number of times while nothing is still getting rendered yet -- I wouldn't say this is something `hudhook` should work around.

Absolutely correct, thank you for the input mate. I'll close this one.
