### ISSUE TITLE
Expose `hooks::common`

### ISSUE THREAD

**Issue by jon-zu** [veeenu/hudhook#85]
For writing customized hooks It would be nice If the module could be exposed somehow, I think It's also easily possible to gate this behind a feature flag.

**Comment by veeenu** [comment]
That's a good idea -- this also would open up the possibility of integrating third party hooks. 

That would make it easier to extend `hudhook` with functionality that's already desirable, like `egui` (cc @Jakobzs), while at the same time not requiring we spread maintenance efforts thin.
