### ISSUE TITLE
Add the option to call the original window proc

### ISSUE THREAD

**Issue by etra0** [veeenu/hudhook#9]
In general, when using the custom window procedure things get a bit hairy, resize stops working and focus acts weird.

I think a _good enough_ solution would be to have the option to call the original WindowProc when input is not being used (i.e. the 'mod' is not capturing anything).

If that sounds ok to you I might try to do it.

**Comment by etra0** [comment]
Nevermind, I misunderstood some bits of winapi.

**Comment by veeenu** [comment]
You mentioned resizing issues: those are definitely still there for DX11. The solution which I adopted for DX12 was to add a hook to `ResizeBuffers` which resets the renderer to deal with the new resolution, chances are the same can be done for DX11.
